# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Mytrip-pool

steps:
- script: |
    cd /home/ubuntu/Tourism
    git pull
    npm install
    npm run build
    pm2 restart $(service-name)
  displayName: 'npm install and build'
