# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Mytrip-pool

steps:
- script: >
    #!/bin/bash

    cd $(Build.Repository.LocalPath)
    git pull

    npm install

    npm run build

    pm2 restart $(service-name)

    pm2 save

  
